"""Initial relational schema"""

import sqlalchemy as sa

from alembic import op

revision = "9f899d7db5f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("app_name", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=12), nullable=False),
        sa.Column("idle_seconds", sa.Integer(), nullable=False),
        sa.CheckConstraint("ends_at > starts_at"),
        sa.CheckConstraint("state IN ('active', 'idle', 'unknown')"),
        sa.CheckConstraint("idle_seconds >= 0"),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_activity_events_ends_at"), ["ends_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_activity_events_received_at"), ["received_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_starts_at"), ["starts_at"], unique=False
        )

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=12), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chat_messages_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "obligations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("weekdays", sa.JSON(), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("end_time", sa.String(length=5), nullable=False),
        sa.Column("start_date", sa.String(length=10), nullable=True),
        sa.Column("end_date", sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("sleep_start", sa.String(length=5), nullable=False),
        sa.Column("sleep_end", sa.String(length=5), nullable=False),
        sa.Column("available_start", sa.String(length=5), nullable=False),
        sa.Column("available_end", sa.String(length=5), nullable=False),
        sa.Column("preferred_start", sa.String(length=5), nullable=False),
        sa.Column("preferred_end", sa.String(length=5), nullable=False),
        sa.Column("break_minutes", sa.Integer(), nullable=False),
        sa.Column("stability_weight", sa.Integer(), nullable=False),
        sa.Column("preferred_weight", sa.Integer(), nullable=False),
        sa.Column("break_weight", sa.Integer(), nullable=False),
        sa.Column("context_weight", sa.Integer(), nullable=False),
        sa.Column("spread_weight", sa.Integer(), nullable=False),
        sa.Column("monitoring_enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint("id = 1"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("goal_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("completed_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=True),
        sa.Column("min_session_minutes", sa.Integer(), nullable=False),
        sa.Column("max_session_minutes", sa.Integer(), nullable=False),
        sa.Column("recurrence", sa.String(length=10), nullable=False),
        sa.Column("sessions_per_week", sa.Integer(), nullable=False),
        sa.Column("activity_apps", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("recurrence IN ('none', 'daily', 'weekly')"),
        sa.CheckConstraint("status IN ('pending', 'completed', 'cancelled')"),
        sa.CheckConstraint("completed_minutes >= 0"),
        sa.CheckConstraint("duration_minutes > 0 AND duration_minutes % 15 = 0"),
        sa.CheckConstraint(
            "min_session_minutes >= 15 AND max_session_minutes >= min_session_minutes"
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5"),
        sa.CheckConstraint("sessions_per_week BETWEEN 1 AND 7"),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_deadline"), ["deadline"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_goal_id"), ["goal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)

    op.create_table(
        "schedule_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("obligation_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("credited_minutes", sa.Integer(), nullable=False),
        sa.CheckConstraint("status IN ('planned', 'completed', 'skipped', 'missed')"),
        sa.CheckConstraint("credited_minutes >= 0"),
        sa.CheckConstraint("ends_at > starts_at"),
        sa.ForeignKeyConstraint(["obligation_id"], ["obligations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedule_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedule_sessions_ends_at"), ["ends_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_schedule_sessions_obligation_id"), ["obligation_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_sessions_starts_at"), ["starts_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_schedule_sessions_task_id"), ["task_id"], unique=False)

    op.create_table(
        "suggestions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("remaining_minutes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('pending', 'confirmed', 'dismissed')"),
        sa.ForeignKeyConstraint(["session_id"], ["schedule_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.bulk_insert(
        sa.table(
            "preferences",
            sa.column("id", sa.Integer()),
            sa.column("timezone", sa.String()),
            sa.column("sleep_start", sa.String()),
            sa.column("sleep_end", sa.String()),
            sa.column("available_start", sa.String()),
            sa.column("available_end", sa.String()),
            sa.column("preferred_start", sa.String()),
            sa.column("preferred_end", sa.String()),
            sa.column("break_minutes", sa.Integer()),
            sa.column("stability_weight", sa.Integer()),
            sa.column("preferred_weight", sa.Integer()),
            sa.column("break_weight", sa.Integer()),
            sa.column("context_weight", sa.Integer()),
            sa.column("spread_weight", sa.Integer()),
            sa.column("monitoring_enabled", sa.Boolean()),
        ),
        [
            {
                "id": 1,
                "timezone": "America/Los_Angeles",
                "sleep_start": "23:00",
                "sleep_end": "07:00",
                "available_start": "07:00",
                "available_end": "23:00",
                "preferred_start": "09:00",
                "preferred_end": "17:00",
                "break_minutes": 15,
                "stability_weight": 8,
                "preferred_weight": 3,
                "break_weight": 10,
                "context_weight": 5,
                "spread_weight": 20,
                "monitoring_enabled": False,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suggestions")
    with op.batch_alter_table("schedule_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_sessions_task_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_sessions_starts_at"))
        batch_op.drop_index(batch_op.f("ix_schedule_sessions_obligation_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_sessions_ends_at"))

    op.drop_table("schedule_sessions")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_index(batch_op.f("ix_tasks_goal_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_deadline"))

    op.drop_table("tasks")
    op.drop_table("preferences")
    op.drop_table("obligations")
    op.drop_table("goals")
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chat_messages_created_at"))

    op.drop_table("chat_messages")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_events_starts_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_received_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_ends_at"))

    op.drop_table("activity_events")
    # ### end Alembic commands ###
